spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL

# OpenAPI 3
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
    enabled: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    groups-order: ASC
    path: /swagger-ui.html

# MyBatis
mybatis:
  mapper-locations: mapper/sample/mysql/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: other
    call-setters-on-nulls: true